[build]
builder = "NIXPACKS"
buildCommand = "./build.sh"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health/simple"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"