[build]
builder = "NIXPACKS"
buildCommand = "./build.sh"

[deploy]
startCommand = "PYTHONPATH=/app python -m uvicorn src.web.app:app --host 0.0.0.0 --port ${PORT} --log-level info"
healthcheckPath = "/health/simple"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"